accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('signup/done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('profile/<int:user_id>/edit',
         views.edit_profile, name='edit_profile'),
    path('profile/<int:post_id>/detail/',
         views.detail_profile, name='detail_profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('introduction/', views.IntroductionView.as_view(), name='introduction'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.create_post, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post,
         name='add_comment_to_post'),
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )

templates/includes/code-highlight.html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
<script>
    const elements = document.getElementsByClassName('markdownx');
    for (element of elements) {
        element.addEventListener('markdownx.update', event => {
            for (const block of document.querySelectorAll('pre code')) {
                hljs.highlightBlock(block);
            }
        });
    }
</script>

templates/includes/footer.html
<ul class="horizontal-list">
    <li class="horizontal-item">
        <a href="https://github.com/Kudoas/KudoLog">GitHub <i class="fab fa-github"></i></a>
    </li>
    <li class="horizontal-item">
        <a href="https://twitter.com/kudoadd">Twitter <i class="fab fa-twitter"></i></a>
    </li>
    <li class="horizontal-item"><a href="{% url 'blog:policy' %}">Policy <i class="far fa-flag"></i></a></li>
    <p class="copyright">Copyright © 2020 KudoLog</p>
</ul>

templates/includes/navigation.html
<nav class="global-nav">
    <ul>
        <li class="nav-item logo"></li>
        <li class="nav-item {% if request.path == '/' %} active {%endif%}">
            <a href="{% url 'blog:post_list' %}">Home</a>
        </li>
        <li class="nav-item {% if request.path == '/about/' %} active {%endif%}">
            <a href="{% url 'blog:about' %}">KudoLogとは</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item {% if request.path == '/post/new/' %} active {%endif%}">
            <a href="{% url 'blog:post_new' %}">New Post <i class="fas fa-vote-yea"></i></a>
        </li>
        <li class="nav-item {% if request.path == '/drafts/' %} active {%endif%}">
            <a href="{% url 'blog:post_draft_list' %}">Draft <i class="fas fa-pencil-alt"></i></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:edit_profile' user.id%}">
                {% if user.display_name %}{{ user.display_name }}{% else %}名無し{% endif %}
                {% if user.icon %}
                <img src="{{ user.icon.url }}" alt='thumbnail' class="thumbnail" width="20" height="20" />
                {% else %}
                <i class="fas fa-user-circle"></i>
                {% endif %}
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'login' %}">Guest <i class="fa fa-user" aria-hidden="true"></i></a>
        </li>
        <li class="nav-item">
            <a href="{% url 'login' %}" aria-label="Login">
                LogIn <i class="fas fa-sign-in-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:signup' %}">SignUp <i class="fas fa-user-plus"></i></a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/includes/page.html
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

templates/includes/post-delete-modal.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                本当に削除しますか？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn dismissed" data-dismiss="modal">キャンセル</button>
                <form method="post" action="{% url 'blog:post_remove' pk=post.pk %}">{% csrf_token %}
                    <button class="btn danger" type="submit">削除</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/includes/post-image.html
{% load static %}

{% if post.category ==  'general'%}
<img class="post-img" src="{% static 'image/post-images/general.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'world' %}
<img class="post-img" src="{% static 'image/post-images/world.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'political economy' %}
<img class="post-img" src="{% static 'image/post-images/economy.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'liviing' %}
<img class="post-img" src="{% static 'image/post-images/living.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'study' %}
<img class="post-img" src="{% static 'image/post-images/study.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'technology' %}
<img class="post-img" src="{% static 'image/post-images/technology.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'interesting' %}
<img class="post-img" src="{% static 'image/post-images/interesting.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'entertainment' %}
<img class="post-img" src="{% static 'image/post-images/entertainment.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'anime&games' %}
<img class="post-img" src="{% static 'image/post-images/games.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% elif post.category == 'home appliance' %}
<img class="post-img" src="{% static 'image/post-images/home-appliance.jpg' %}" alt="{% static 'image/voyage.jpg' %}">
{% endif %}

templates/includes/profile-edit-modal.html
<!-- iconModal -->
<div class="modal fade" id="iconModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">アイコンの編集</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ icon_form.as_p }}
                    <button type="submit" class="save btn btn-outline-primary">変更を保存</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- displayNameModal -->
<div class="modal fade" id="displayNameModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ユーザー名の編集</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ rename_form.as_p }}
                    <button type="submit" class="save btn btn-outline-primary">変更を保存</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- profileModal -->
<div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">プロフィール情報の編集</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ profile_form.as_p }}
                    <button type="submit" class="save btn btn-outline-primary">変更を保存</button>
                </form>
            </div>
        </div>
    </div>
</div>