accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('signup/done/', views.SignupDoneView.as_view(), name='signup_done'),
    path('profile/<int:user_id>/edit',
         views.edit_profile, name='edit_profile'),
    path('profile/<int:post_id>/detail/',
         views.detail_profile, name='detail_profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('introduction/', views.IntroductionView.as_view(), name='introduction'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.create_post, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post,
         name='add_comment_to_post'),
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT
                          )

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone
from markdownx.models import MarkdownxField

from accounts.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_img = models.ImageField(upload_to='post', blank=True)
    title = models.CharField(max_length=200)
    CATEGORY_CHOICES = (
        ('general', '一般'),
        ('world', '世の中'),
        ('political economy', '政治と経済'),
        ('liviing', '暮らし'),
        ('study', '学び'),
        ('technology', 'テクノロジー'),
        ('interesting', 'おもしろ'),
        ('entertainment', 'エンタメ'),
        ('anime&games', 'アニメとゲーム'),
        ('home appliance', '家電'),
    )
    category = models.CharField(
        max_length=50, blank=True, choices=CATEGORY_CHOICES
    )
    text = MarkdownxField(help_text='Markdownに対応しています')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def late_five_post(self):
        return self.post_set.order_by('published_date').reverse[:4]

    def summary(self):
        return self.text[:50]

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'blog.Post', related_name='comments', on_delete=models.CASCADE
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog/post_list')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from markdownx.widgets import MarkdownxWidget
from markdownx.fields import MarkdownxFormField

from .models import Post, Comment


class PostModelForm(forms.ModelForm):

    def __init__(self, *arg, **kwarg):
        super().__init__(*arg, **kwarg)
        self.fields['text'].widget = MarkdownxWidget()
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = ('title', 'category', 'text')


CATEGORY_CHOICES = (
    ('general', '一般'),
    ('world', '世の中'),
    ('political economy', '政治と経済'),
    ('living', '暮らし'),
    ('study', '学び'),
    ('technology', 'テクノロジー'),
    ('interesting', 'おもしろ'),
    ('entertainment', 'エンタメ'),
    ('anime&games', 'アニメとゲーム'),
    ('home appliance', '家電'),
)


class PostForm(forms.Form):
    def __init__(self, *arg, **kwarg):
        super().__init__(*arg, **kwarg)
        self.fields['text'].widget = MarkdownxWidget()
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    post_img = forms.ImageField(required=False)
    title = forms.CharField(max_length=200)
    category = forms.ChoiceField(
        widget=forms.Select,
        choices=CATEGORY_CHOICES,
        required=True,
    )
    text = MarkdownxFormField(help_text='Markdownに対応しています')


class CategorySearchForm(forms.Form):
    category = forms.ChoiceField(
        widget=forms.Select,
        choices=CATEGORY_CHOICES,
        required=False,
    )


class CommentForm(forms.ModelForm):

    def __init__(self, *arg, **kwarg):
        super().__init__(*arg, **kwarg)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView

from accounts.models import User
from .forms import PostModelForm, PostForm, CategorySearchForm, CommentForm
from .models import Comment, Post


class IntroductionView(TemplateView):
    template_name = 'blog/introduction.html'


class PolicyView(TemplateView):
    template_name = 'blog/policy.html'


class AboutView(TemplateView):
    template_name = 'blog/about.html'


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    paginate_by = 12

    def get_context_data(self):
        context = super().get_context_data()
        context['category_form'] = CategorySearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = Post.objects.filter(
            published_date__lte=timezone.now()
        ).order_by('-published_date')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword) |
                Q(author__display_name__icontains=keyword) |
                Q(author__username__icontains=keyword)
            )

        category_form = CategorySearchForm(self.request.GET)
        if category_form.is_valid():
            category = category_form.cleaned_data['category']
            if category:
                queryset = queryset.filter(category=category)
        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class DraftListView(LoginRequiredMixin, ListView):
    model = Post
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True, author=self.request.user).order_by('-created_date')


@login_required
def create_post(request):
    form = PostForm(request.POST, request.FILES or None)
    if request.method == 'POST' and form.is_valid():
        post = Post()
        post.post_img = form.cleaned_data['post_img']
        post.title = form.cleaned_data['title']
        post.category = form.cleaned_data['category']
        post.text = form.cleaned_data['text']
        post.author = request.user
        Post.objects.create(
            post_img=post.post_img,
            title=post.title,
            category=post.category,
            author=post.author,
            text=post.text,
            created_date=timezone.now()
        )
        return redirect('blog:post_draft_list')
    return render(request, 'blog/post_form.html', {'post_form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post_form = PostModelForm(request.POST or None, instance=post)
    if request.method == 'POST' and post_form.is_valid():
        post_form.save(commit=False)
        post.published_date = timezone.now()
        post_form.save()
        return redirect('blog:post_detail', pk=pk)
    context = {'post_form': post_form}
    return render(request, 'blog/post_edit.html', context)


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
    return redirect('blog:post_list')


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail.html', pk=pk)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

templates/blog/about.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog/index.css' %}" />
{% endblock %}

{% block content %}
<div class="container">
    <h1 style="text-align: center"><span style="font-family: 'Dancing Script', cursive;">KudoLog</span></h1>
    <article>
        <h2><span style="font-family: 'Dancing Script', cursive;">KudoLog</span>とは</h2>
        <p class="lead"><span style="font-family: 'Dancing Script', cursive;">KudoLog</span>は自由に書き込める掲示板アプリです。</p>
        <h2><span style="font-family: 'Dancing Script', cursive;">KudoLog</span>の使い方</h2>
        <p>ユーザー登録しない場合とする場合で機能が異なります。</p>
        <section>
            <h3>登録なし</h3>
            <p>それぞれの記事を閲覧できます。</p>
            <h3>登録あり</h3>
            <p>登録ユーザーは以下のことが行えます。</p>
            <ul>
                <li>プロフィール作成</li>
                <li>記事の下書き作成</li>
                <li>記事の発行</li>
                <li>記事に対するコメント</li>
            </ul>
            <p>記事を作成するとDraftへ保存されます。Draftの記事を投稿すると公開されます。
                <br>自分の記事に来たコメントに返信する場合は、<strong>@誰々</strong>のようにメンションを取りましょう。
            </p>
        </section>
        <h2>注意事項</h2>
        <p>下書きを編集し保存するとそのまま投稿されます。再編集したい場合は投稿済みの記事からできます。</p>
        <h2>その他</h2>
        <p>内容は自由ですが、誹謗中傷はないようにお願い致します。</p>
    </article>
</div>
{% endblock %}

templates/blog/comment_form.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog/post.css' %}" />
{% endblock%}

{% block content %}
<div class="container">
    <h1>コメントの作成</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{form.as_p}}
        <div class="btn-wrapper">
            <button type="submit" class="btn btn-outline-primary">作成</button>
        </div>
    </form>
</div>
{% endblock %}

templates/blog/introduction.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Daichi Kudo</h1>
</div>
{% endblock %}

templates/blog/policy.html
{% extends 'base.html' %}
{% block content %}

<article>
    <div class="container">
        <p></p>
        <h1>利用規約</h1>
        <p>
            この利用規約（以下、「本規約」といいます。）は、Daichi Kudo（以下、「管理人」といいます。）がこのウェブサイト上で提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。
            ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。
        </p>
        <section class="mb-2">
            <h2>
                第1条（適用）
            </h2>
            本規約は、ユーザーと管理人との間の本サービスの利用に関わる一切の関係に適用されるものとします。
            管理人は本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず、本規約の一部を構成するものとします。
            本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。
        </section>
        <section class="mb-2">
            <h2>
                第2条（利用登録）
            </h2>
            <p>
                本サービスにおいては、登録希望者が本規約に同意の上、管理人の定める方法によって利用登録を申請し、管理人がこの承認を登録希望者に通知することによって、利用登録が完了するものとします。
                管理人は、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。
                利用登録の申請に際して虚偽の事項を届け出た場合
                本規約に違反したことがある者からの申請である場合
                その他、管理人が利用登録を相当でないと判断した場合
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第3条（ユーザーIDおよびパスワードの管理）
            </h2>
            <p>
                ユーザーは、自己の責任において、本サービスのユーザーIDおよびパスワードを適切に管理するものとします。
                ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与し、もしくは第三者と共用することはできません。管理人は、ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのユーザーIDを登録しているユーザー自身による利用とみなします。
                ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は、管理人に故意又は重大な過失がある場合を除き、管理人は一切の責任を負わないものとします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第4条（禁止事項）
            </h2>
            <p>
                ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。
                法令または公序良俗に違反する行為 犯罪行為に関連する行為
                管理人、本サービスの他のユーザー、または第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為
                管理人のサービスの運営を妨害するおそれのある行為
                他のユーザーに関する個人情報等を収集または蓄積する行為
                不正アクセスをし、またはこれを試みる行為 他のユーザーに成りすます行為
                管理人のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為
                管理人、本サービスの他のユーザーまたは第三者の知的財産権、肖像権、プライバシー、名誉その他の権利または利益を侵害する行為
                以下の表現を含み、または含むと管理人が判断する内容を本サービス上に投稿し、または送信する行為
                過度に暴力的な表現 露骨な性的表現
                人種、国籍、信条、性別、社会的身分、門地等による差別につながる表現
                自殺、自傷行為、薬物乱用を誘引または助長する表現
                その他反社会的な内容を含み他人に不快感を与える表現
                以下を目的とし、または目的とすると管理人が判断する行為
                営業、宣伝、広告、勧誘、その他営利を目的とする行為（管理人の認めたものを除きます。）
                性行為やわいせつな行為を目的とする行為
                面識のない異性との出会いや交際を目的とする行為
                他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為
                管理人、本サービスの他のユーザー、または第三者に不利益、損害または不快感を与えることを目的とする行為
                その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為
                宗教活動または宗教団体への勧誘行為 その他、管理人が不適切と判断する行為
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第5条（本サービスの提供の停止等）
            </h2>
            <p>
                管理人は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
                本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
                地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合
                コンピュータまたは通信回線等が事故により停止した場合
                その他、管理人が本サービスの提供が困難と判断した場合
                管理人は、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第6条（著作権）
            </h2>
            <p>
                ユーザーは、自ら著作権等の必要な知的財産権を有するか、または必要な権利者の許諾を得た文章、画像や映像等の情報に関してのみ、本サービスを利用し、投稿ないしアップロードすることができるものとします。
                ユーザーが本サービスを利用して投稿ないしアップロードした文章、画像、映像等の著作権については、当該ユーザーその他既存の権利者に留保されるものとします。ただし、管理人は、本サービスを利用して投稿ないしアップロードされた文章、画像、映像等について、本サービスの改良、品質の向上、または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし、ユーザーは、この利用に関して、著作者人格権を行使しないものとします。
                前項本文の定めるものを除き、本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて管理人または管理人にその利用を許諾した権利者に帰属し、ユーザーは無断で複製、譲渡、貸与、翻訳、改変、転載、公衆送信（送信可能化を含みます。）、伝送、配布、出版、営業使用等をしてはならないものとします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第7条（利用制限および登録抹消）
            </h2>
            <p>
                管理人は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、投稿データを削除し、ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
                本規約のいずれかの条項に違反した場合
                本サービスについて、最終の利用から一定期間利用がない場合
                その他、管理人が本サービスの利用を適当でないと判断した場合
                管理人は、本条に基づき管理人が行った行為によりユーザーに生じた損害について、一切の責任を負いません。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第8条（退会）
            </h2>
            <p>
                ユーザーは、管理人の定める退会手続により、本サービスから退会できるものとします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第9条（保証の否認および免責事項）
            </h2>
            <p>
                管理人は、本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
                管理人は、本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし、本サービスに関する管理人とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。
                前項ただし書に定める場合であっても、管理人は、管理人の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（管理人またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について一切の責任を負いません。また、管理人の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は、ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
                管理人は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第10条（サービス内容の変更等）
            </h2>
            <p>
                管理人は、ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第11条（利用規約の変更）
            </h2>
            <p>
                管理人は、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお、本規約の変更後、本サービスの利用を開始した場合には、当該ユーザーは変更後の規約に同意したものとみなします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第12条（個人情報の取扱い）
            </h2>
            <p>
                管理人は、本サービスの利用によって取得する個人情報については、管理人「プライバシーポリシー」に従い適切に取り扱うものとします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第13条（通知または連絡）
            </h2>
            <p>
                ユーザーと管理人との間の通知または連絡は、管理人の定める方法によって行うものとします。管理人は、ユーザーから管理人が別途定める方式に従った変更届け出がない限り、現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い、これらは発信時にユーザーへ到達したものとみなします。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第14条（権利義務の譲渡の禁止）
            </h2>
            <p>
                ユーザーは、管理人の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。
            </p>
        </section>
        <section class="mb-2">
            <h2>
                第15条（準拠法・裁判管轄）
                本規約の解釈にあたっては、日本法を準拠法とします。
            </h2>
            <p>
                本サービスに関して紛争が生じた場合には、管理人の所在地を管轄する裁判所を専属的合意管轄とします。
            </p>
        </section>
        <p>
            以上
        </p>
    </div>
</article>

{% endblock %}

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <p></p>
    <form action="" method="post">{% csrf_token %}
        <h3>"{{ object }}"を削除してもよろしいですか。</h3>
        <input class='btn btn-danger' type="submit" value='削除する' />
    </form>
    <p></p>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdown %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog/post.css' %}" />
{% endblock%}

{% block content %}
<div class="content">
    <div class="container">
        <article>
            <header>
                <h1>{{ post.title }}</h1>
                <div class="date">
                    <p>
                        Published:{{ post.created_date.date }} Edited:{{ post.published_date.date }}
                        [<a href="#">{{post.category}}</a>]
                    </p>
                </div>
                {% if post.post_img %}
                <div class="post-image-wrapper">
                    <img src=" {{ post.post_img.url }}" alt="post-image" class="post-image">
                </div>
                {% endif %}
                {% if user.is_authenticated and request.user == post.author %}
                <div class="btn-wrapper1">
                    <a class="btn btn-outline-primary" href="{% url 'blog:post_edit' post.pk %}">編集</a>
                    <button type="button" class="btn danger" data-toggle="modal" data-target="#deleteModal">
                        削除
                    </button>
                </div>
                {% include 'includes/post-delete-modal.html' %}
                {% endif %}
            </header>
            <section>
                {{ post.text | safe | markdown_to_html }}
            </section>
            <footer class="text-author">
                <a href="{% url 'accounts:detail_profile' post.id %}">
                    <p>Text {{ post.author.display_name }}@{{ post.author.username }}</p>
                </a>
            </footer>
        </article>
        <section class="comment">
            {% for comment in post.comments.all %}
            <div class="card">
                <div class="content">
                    <p> 投稿者:{{ comment.author.display_name }}@{{ comment.author.username }}
                        <br>{{ comment.create_date }}</br></p>
                    <p>{{ comment.text|safe|linebreaksbr }}</p>
                    {% if not comment.approved_comment %}
                    <a class="btn btn-outline-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
                        コメント投稿する
                    </a>
                    <a class="btn danger" href="{% url 'blog:comment_remove' pk=comment.pk %}">
                        コメント削除する
                    </a>
                    {% endif %}
                </div>
            </div>
            {% empty %}
            <p>まだコメントはありません</p>
            {% endfor %}
            {% if user.is_authenticated %}
            <div class="btn-wrapper">
                <a class="btn" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">コメントする</a>
            </div>
            {% endif %}
        </section>
    </div>
</div>
{% include 'includes/code-highlight.html' %}
{% endblock %}

templates/blog/post_draft_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <p>{{ object }}を消していいですか？</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
</div>
{% endblock %}

templates/blog/post_draft_list.html
{% extends 'base.html' %}
{% load static %}
{% load markdown %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog/post.css' %}" />
{% endblock%}

{% block content %}
<div class="container">
    <h1>下書き一覧</h1>
    {% for post in post_list %}
    <hr class="hr">
    <article>
        <header>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <div class="date">
                <p>
                    Published:{{ post.created_date.date }} Edited:{{ post.published_date.date }}
                    [<a href="#">{{post.category}}</a>]
                </p>
            </div>
        </header>
        <section>
            <p>{{ post.text | markdown_to_html | linebreaksbr }}</p>
        </section>
        <footer>
            <footer class="text-author">
                <a href="{% url 'accounts:detail_profile' post.id %}">
                    <p>Text {{ post.author.display_name }}@{{ post.author.username }}</p>
                </a>
            </footer>
        </footer>
        <div class="btn-wrapper">
            <a class="btn" href="{% url 'blog:post_publish' pk=post.pk %}">投稿する</a>
        </div>
        {% empty %}
        <p>下書きはありません</p>
    </article>
    {% endfor %}
</div>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog/post.css' %}" />
{% endblock%}
<div class="container">
    <h1>記事の編集</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_form.as_p }}
        {{ post_form.media }}
        <div class="btn-wrapper">
            <button type="submit" class="btn">保存</button>
        </div>
    </form>
    {% include 'includes/code-highlight.html' %}
</div>
{% endblock %}